/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelontongid;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import app.Login;
import app.Session;

/**
 *
 * @author user
 */
public class AdminForm extends javax.swing.JFrame {
    private DefaultTableModel tabmode;
    private ResultSet hasil;
    private String panelActive = "PENJUALAN";
    
    CrudUsers userModel = new CrudUsers();
    CrudBarang barangModel = new CrudBarang();
    CrudTransaksi trxModel = new CrudTransaksi();
    /**
     * Creates new form BarangForm
     */
    public AdminForm() {
        initComponents();
        dataTable();
    }
    
    public void setPanel(String str){
        this.panelActive = str;
    }
    
    public void dataTable(){
        if(panelActive == "USERS"){
            tampil_users();
        }else if(panelActive == "BARANG"){
            tampil_barang();
        }else if(panelActive == "PEMBELIAN"){
            tampil_transaksi("BELI");
        }else if(panelActive == "PENJUALAN"){
            tampil_transaksi("JUAL");
        }
        lbl_title.setText(panelActive);
    }
    
    public void table_transaksi(){
        Object [] baris = {"ID","Nama Barang","Jumlah","Nominal","Waktu Transaksi","Dibuat Oleh"};
        tabmode = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        data_table.setModel(tabmode);
        try {
            while (hasil.next()){
                String[] data = {
                    hasil.getString("id"),
                    hasil.getString("nama_barang"),
                    hasil.getString("qty"),
                    hasil.getString("nominal"),
                    hasil.getString("created_at"),
                    hasil.getString("nama")
                };
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            
        }
    }
    public void tampil_transaksi(String jenis){
        hasil = trxModel.tampilData(jenis);
        table_transaksi();
    }
    public void cari_transaksi(String str,String jenis){
        hasil = trxModel.cariData(str,jenis);
        table_transaksi();
    }
//    Barang
    public void table_barang(){
        Object [] baris = {"ID","Nama Barang","Stok","Harga"};
        tabmode = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        data_table.setModel(tabmode);
        try {
            while (hasil.next()){
                String[] data = {
                    hasil.getString("id"),
                    hasil.getString("nama_barang"),
                    hasil.getString("stok"),
                    hasil.getString("harga")
                };
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            
        }
    }
    public void tampil_barang(){
        hasil = barangModel.tampilData();
        table_barang();
    }
    public void cari_barang(String str){
        hasil = barangModel.cariData(str);
        table_barang();
    }
    
//    USER
    public void table_users(){
        Object [] baris = {"Username","Nama","Role"}; 
        tabmode = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        data_table.setModel(tabmode);
        try {
            while (hasil.next()){
                String[] data = {hasil.getString("username"),hasil.getString("nama"),hasil.getString("role")};
                tabmode.addRow(data);
            }
        } catch (Exception e) {
            
        }
    }
    
//    method untuk menampilkan data ke tabel_siswa [JTable] 
    public void tampil_users(){
        hasil = userModel.tampilData();
        table_users();
    }
    
    public void cari_user(String str){
        hasil = userModel.cariData(str);
        table_users();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_penjualan = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_pembelian = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_barang = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_users = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        data_table = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        txt_cari = new javax.swing.JTextField();
        btn_cari = new javax.swing.JButton();
        btn_all = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(66, 123, 198));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\user\\Pictures\\Untitled-1-.png")); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 144, -1));

        lbl_penjualan.setBackground(new java.awt.Color(143, 192, 247));
        lbl_penjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_penjualanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_penjualanMousePressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelontongid/image/transaksi.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Penjualan");

        javax.swing.GroupLayout lbl_penjualanLayout = new javax.swing.GroupLayout(lbl_penjualan);
        lbl_penjualan.setLayout(lbl_penjualanLayout);
        lbl_penjualanLayout.setHorizontalGroup(
            lbl_penjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_penjualanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        lbl_penjualanLayout.setVerticalGroup(
            lbl_penjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(lbl_penjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 92, 145, 40));

        lbl_pembelian.setBackground(new java.awt.Color(143, 192, 247));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelontongid/image/transaksi.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pembelian");

        javax.swing.GroupLayout lbl_pembelianLayout = new javax.swing.GroupLayout(lbl_pembelian);
        lbl_pembelian.setLayout(lbl_pembelianLayout);
        lbl_pembelianLayout.setHorizontalGroup(
            lbl_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_pembelianLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        lbl_pembelianLayout.setVerticalGroup(
            lbl_pembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(lbl_pembelian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 145, 40));

        lbl_barang.setBackground(new java.awt.Color(143, 192, 247));
        lbl_barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_barangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_barangMousePressed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelontongid/image/path2.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Barang");

        javax.swing.GroupLayout lbl_barangLayout = new javax.swing.GroupLayout(lbl_barang);
        lbl_barang.setLayout(lbl_barangLayout);
        lbl_barangLayout.setHorizontalGroup(
            lbl_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_barangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        lbl_barangLayout.setVerticalGroup(
            lbl_barangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(lbl_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 189, 145, 40));

        lbl_users.setBackground(new java.awt.Color(143, 192, 247));
        lbl_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_usersMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbl_usersMousePressed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kelontongid/image/g4584.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Users");

        javax.swing.GroupLayout lbl_usersLayout = new javax.swing.GroupLayout(lbl_users);
        lbl_users.setLayout(lbl_usersLayout);
        lbl_usersLayout.setHorizontalGroup(
            lbl_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lbl_usersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        lbl_usersLayout.setVerticalGroup(
            lbl_usersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(lbl_users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 145, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(66, 123, 198));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Logout");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_title.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_title.setForeground(new java.awt.Color(255, 255, 255));
        lbl_title.setText("TITLE");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 559, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_title, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        jPanel6.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, -1));

        data_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        data_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                data_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(data_table);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 142, 680, 370));

        jButton2.setText("Tambah Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 102, -1, -1));

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        jPanel6.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 102, -1, -1));

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel6.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 102, -1, -1));
        jPanel6.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 103, 250, -1));

        btn_cari.setText("Cari");
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        jPanel6.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, -1, -1));

        btn_all.setText("Tampilkan semua");
        btn_all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_allActionPerformed(evt);
            }
        });
        jPanel6.add(btn_all, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        if(panelActive == "USERS"){
            UserForm user = new UserForm();
            user.setVisible(true);
        }else if(panelActive == "PEMBELIAN"){
            
        }else if(panelActive == "PENJUALAN"){
            PenjualanForm addPenjualan = new PenjualanForm();
            addPenjualan.setVisible(true);
        }else if(panelActive == "BARANG"){
            BarangForm barang = new BarangForm();
            barang.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void data_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_data_tableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_data_tableMouseClicked

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        try { 
            if(data_table.getSelectedRow() >= 0) {
                String id = data_table.getValueAt(data_table.getSelectedRow(),0).toString();
                dispose();
                if(panelActive == "USERS"){
                    UserForm user = new UserForm(id);
                    user.setVisible(true);
                }else if(panelActive == "PEMBELIAN"){
                    
                }else if(panelActive == "PENJUALAN"){
                    PenjualanEditForm editTrx = new PenjualanEditForm(id);
                    editTrx.setVisible(true);
                }else if(panelActive == "BARANG"){
                    BarangForm barang = new BarangForm(id);
                    barang.setVisible(true);
                }
             }
             else {
                JOptionPane.showMessageDialog(null, "Belum ada data yang dipilih!");
             }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
        if(txt_cari.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Masukan kata pencarian dahulu!");
        }else{
            if(panelActive == "USERS"){
                cari_user(txt_cari.getText());
            }else if(panelActive == "BARANG"){
                cari_barang(txt_cari.getText());
            }else if(panelActive == "PENJUALAN"){
                cari_transaksi(txt_cari.getText(), "JUAL");
            }
        }
    }//GEN-LAST:event_btn_cariActionPerformed

    private void btn_allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_allActionPerformed
        // TODO add your handling code here:
        txt_cari.setText("");
        if(panelActive == "USERS"){
            tampil_users();
        }else if(panelActive == "BARANG"){
            tampil_barang();
        }else if(panelActive == "PENJUALAN"){
            tampil_transaksi("JUAL");
        }
    }//GEN-LAST:event_btn_allActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        try { 
            if(data_table.getSelectedRow() >= 0) {
                String id = data_table.getValueAt(data_table.getSelectedRow(),0).toString();
                if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ?","Warning",2) == JOptionPane.YES_OPTION){
                    try {
                        String msg = "";
                        if(panelActive == "USERS"){
                            msg = userModel.hapusData(id,"username");
                            tampil_users();
                        }else if(panelActive == "PEMBELIAN"){

                        }else if(panelActive == "PENJUALAN"){
                            ResultSet trx = trxModel.getById(id);
                            try {
                                trx.next();
                                barangModel.editStok("+", trx.getString("barang_id"), trx.getString("qty"));
                                msg = trxModel.hapusData(id);
                                tampil_transaksi("JUAL");
                            } catch (Exception e) {
                                msg = e.getMessage();
                            }
                        }else if(panelActive == "BARANG"){
                            msg = barangModel.hapusData(id);
                            tampil_barang();
                        }
                        JOptionPane.showMessageDialog(null, msg , "Informasi",JOptionPane.INFORMATION_MESSAGE);
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Data gagal dihapus" , "Informasi", 
                        JOptionPane.INFORMATION_MESSAGE);
                    }
                }
             }
             else {
                JOptionPane.showMessageDialog(null, "Belum ada data yang dipilih!");
             }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.Logout(Session.getUserId());
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lbl_penjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_penjualanMouseClicked

    }//GEN-LAST:event_lbl_penjualanMouseClicked

    private void lbl_barangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_barangMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbl_barangMouseClicked

    private void lbl_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lbl_usersMouseClicked

    private void lbl_usersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_usersMousePressed
        // TODO add your handling code here:
        panelActive = "USERS";
        dataTable();
    }//GEN-LAST:event_lbl_usersMousePressed

    private void lbl_barangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_barangMousePressed
        panelActive = "BARANG";
        dataTable();
    }//GEN-LAST:event_lbl_barangMousePressed

    private void lbl_penjualanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_penjualanMousePressed
        panelActive = "PENJUALAN";
        dataTable();
    }//GEN-LAST:event_lbl_penjualanMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_all;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JTable data_table;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel lbl_barang;
    private javax.swing.JPanel lbl_pembelian;
    private javax.swing.JPanel lbl_penjualan;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JPanel lbl_users;
    private javax.swing.JTextField txt_cari;
    // End of variables declaration//GEN-END:variables
}
