/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kelontongid;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class PenjualanForm extends javax.swing.JFrame {

    /**
     * Creates new form PembelianForm
     */
    private int index = -1;
    private DefaultComboBoxModel cbModel;
    private CrudBarang barangModel = new CrudBarang();
    private CrudTransaksi trxModel = new CrudTransaksi();
    private ResultSet dataBarang;
    private AdminForm admin = new AdminForm();
    private DefaultTableModel tabmode;
    
    public PenjualanForm() {
        initComponents();
        cbBarang();
        Object [] baris = {"ID","Nama Barang","Jumlah","Harga Satuan","Total Harga"};
        tabmode = new DefaultTableModel(null, baris) {
            public boolean isCellEditable(int row, int column) {
               return false;
            }
        };
        tabel_trx.setModel(tabmode);
    }
    
    private void cbBarang(){
        cbModel = new DefaultComboBoxModel();
        cb_barang.setModel(cbModel);
        dataBarang = barangModel.stokAda();
        try {
            cb_barang.addItem("Pilih Barang");
            while(dataBarang.next()){   
                cb_barang.addItem(dataBarang.getString("id")+"-"+dataBarang.getString("nama_barang"));
            }
        } catch (Exception e) {
            
        }
    }
    
    private boolean cekTabel(String str){
        boolean result = false;
        for (int row = 0; row < tabel_trx.getRowCount(); row++){
            if(tabel_trx.getValueAt(row, 0).toString().equals(str)){
                result = true;
            }
        }
        return result;
    }
    
    private void setTotal(){
        int total = 0;
        for (int row = 0; row < tabel_trx.getRowCount(); row++){
            total += Integer.parseInt(tabel_trx.getValueAt(row, 4).toString());
        }
        txt_totaltransaksi.setText(Integer.toString(total));
    }
    
    private void reset_text() {
        txt_totalHarga.setText("");
        txt_harga.setText("");
        txt_barangId.setText("");
        txt_jumlah.setText("");
        cb_barang.setSelectedIndex(0);
        index = -1;
    }
    
    private void exitForm(){
        dispose();
        admin.tampil_transaksi("JUAL");
        admin.setVisible(true);
    }
    
    private void setBarangDetail(String id){
        dataBarang = barangModel.getById(id);
        try {
            dataBarang.next();
            txt_barangId.setText(dataBarang.getString("id"));
            txt_harga.setText(dataBarang.getString("harga"));
            int jumlah = 1;
            if(!txt_jumlah.getText().trim().equals("")){
                if (!txt_jumlah.getText().trim().matches("[0-9]+")){
                    JOptionPane.showMessageDialog(null,"Jumlah tidak valid!");
                    txt_jumlah.setText("");
                    txt_jumlah.requestFocus();
                }else{
                    jumlah = Integer.parseInt(txt_jumlah.getText().trim());
                }
            }
            jumlah = Integer.parseInt(dataBarang.getString("harga")) * jumlah;
            txt_totalHarga.setText(Integer.toString(jumlah));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_keluar = new javax.swing.JButton();
        txt_harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_jumlah = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_totalHarga = new javax.swing.JTextField();
        cb_barang = new javax.swing.JComboBox<>();
        txt_barangId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_trx = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btn_simpanAll = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_tambah = new javax.swing.JButton();
        txt_totaltransaksi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(66, 123, 198));

        jPanel1.setBackground(new java.awt.Color(143, 192, 247));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("PENJUALAN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 70));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Daftar Penjualan");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        btn_reset.setBackground(new java.awt.Color(66, 123, 198));
        btn_reset.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel2.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(237, 380, 100, 30));

        btn_hapus.setBackground(new java.awt.Color(66, 123, 198));
        btn_hapus.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_hapus.setForeground(new java.awt.Color(255, 255, 255));
        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel2.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 380, 80, 30));

        btn_keluar.setBackground(new java.awt.Color(66, 123, 198));
        btn_keluar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_keluar.setForeground(new java.awt.Color(255, 255, 255));
        btn_keluar.setText("Keluar");
        btn_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_keluarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, 30));

        txt_harga.setEditable(false);
        txt_harga.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_harga.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_harga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 123, 198)));
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        jPanel2.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 160, 30));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setText("Harga");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setText("Jumlah");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        txt_jumlah.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_jumlah.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_jumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 123, 198)));
        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });
        jPanel2.add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 320, 30));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setText("Total Harga");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        txt_totalHarga.setEditable(false);
        txt_totalHarga.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_totalHarga.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_totalHarga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 123, 198)));
        txt_totalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalHargaActionPerformed(evt);
            }
        });
        txt_totalHarga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_totalHargaKeyPressed(evt);
            }
        });
        jPanel2.add(txt_totalHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 320, 30));

        cb_barang.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        cb_barang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_barang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_barangItemStateChanged(evt);
            }
        });
        jPanel2.add(cb_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 320, 30));

        txt_barangId.setEditable(false);
        txt_barangId.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txt_barangId.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_barangId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(66, 123, 198)));
        txt_barangId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_barangIdActionPerformed(evt);
            }
        });
        jPanel2.add(txt_barangId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 160, 30));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setText("Kode Barang");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        tabel_trx.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Barang", "Nama Barang", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel_trx.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_trxMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_trx);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 320, 210));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Nama Barang");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        btn_simpanAll.setBackground(new java.awt.Color(66, 123, 198));
        btn_simpanAll.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_simpanAll.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpanAll.setText("Simpan");
        btn_simpanAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanAllActionPerformed(evt);
            }
        });
        jPanel2.add(btn_simpanAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 140, 30));

        btn_ubah.setBackground(new java.awt.Color(66, 123, 198));
        btn_ubah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 90, 30));

        btn_tambah.setBackground(new java.awt.Color(66, 123, 198));
        btn_tambah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btn_tambah.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel2.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 110, 30));

        txt_totaltransaksi.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel2.add(txt_totaltransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 270, 30));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setText("Total :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 716, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        reset_text();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        if(index < 0){
            JOptionPane.showMessageDialog(null,"Maaf, belum ada data dipilih!");
        }else{
            if (JOptionPane.showConfirmDialog(null, "Apakah Anda yakin akan menghapus data ini ?","Warning",2) == JOptionPane.YES_OPTION){
                tabmode.removeRow(tabel_trx.getSelectedRow());
            }else{
                reset_text();
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_keluarActionPerformed
        // TODO add your handling code here:
        exitForm();
    }//GEN-LAST:event_btn_keluarActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed

    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void txt_jumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyPressed

    }//GEN-LAST:event_txt_jumlahKeyPressed

    private void txt_totalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalHargaActionPerformed

    }//GEN-LAST:event_txt_totalHargaActionPerformed

    private void txt_totalHargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_totalHargaKeyPressed

    }//GEN-LAST:event_txt_totalHargaKeyPressed

    private void txt_barangIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_barangIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_barangIdActionPerformed

    private void btn_simpanAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanAllActionPerformed
        // TODO add your handling code here:
        if (tabel_trx.getRowCount() < 1){
            JOptionPane.showMessageDialog(null,"Maaf, data masih kosong!");
        } else {
            try {
                String[] key = {
                    "barang_id","qty","nominal","jenis"
                };
                ArrayList<String> value = new ArrayList<String>();
                String msg = null;
                for (int row = 0; row < tabel_trx.getRowCount(); row++){
                    value.add(tabel_trx.getValueAt(row, 0).toString());
                    value.add(tabel_trx.getValueAt(row, 2).toString());
                    value.add(tabel_trx.getValueAt(row, 4).toString());
                    value.add("JUAL");
                    msg = trxModel.simpanData(key, value);
                    barangModel.editStok("-", tabel_trx.getValueAt(row, 0).toString(), tabel_trx.getValueAt(row, 2).toString());
                    value.clear();
                }
                if(msg.contains("berhasil")){
                    reset_text();
                    tabmode.setRowCount(0);
                    txt_totaltransaksi.setText("");
                }
                JOptionPane.showMessageDialog(null, msg , "Informasi", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Data gagal tersimpan ("+e.getMessage()+")" , "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_simpanAllActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        // TODO add your handling code here:
        if(index < 0){
            JOptionPane.showMessageDialog(null,"Maaf, belum ada data dipilih!");
        }else if (cb_barang.getSelectedIndex() < 1){
            JOptionPane.showMessageDialog(null,"Maaf, pilih terlebih dahulu barang nya!");
        } else if (!txt_jumlah.getText().trim().matches("[0-9]+")){
            JOptionPane.showMessageDialog(null,"Jumlah stok tidak valid!");
            txt_jumlah.setText("");
            txt_jumlah.requestFocus();
        }else {
            String [] barang = cb_barang.getSelectedItem().toString().split("\\-", -1);
            try {
                int stok = Integer.parseInt(dataBarang.getString("stok"));
                if(stok < Integer.parseInt(txt_jumlah.getText())){
                    JOptionPane.showMessageDialog(null,"Maaf, Stok tidak mencukupi!");
                    txt_jumlah.setText("");
                    txt_jumlah.requestFocus();
                }else{
                    tabel_trx.setValueAt(barang[0], index, 0);
                    tabel_trx.setValueAt(barang[1], index, 1);
                    tabel_trx.setValueAt(txt_jumlah.getText(), index, 2);
                    tabel_trx.setValueAt(txt_harga.getText(), index, 3);
                    tabel_trx.setValueAt(txt_totalHarga.getText(), index, 4);
                    setTotal();
                    reset_text();
                    JOptionPane.showMessageDialog(null,"Data berhasil diubah!");
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        if (cb_barang.getSelectedIndex() < 1){
            JOptionPane.showMessageDialog(null,"Maaf, pilih terlebih dahulu barang nya!");
        } else if (!txt_jumlah.getText().trim().matches("[0-9]+")){
            JOptionPane.showMessageDialog(null,"Jumlah stok tidak valid!");
            txt_jumlah.setText("");
            txt_jumlah.requestFocus();
        }else {
            String [] barang = cb_barang.getSelectedItem().toString().split("\\-", -1);
            try {
                int stok = Integer.parseInt(dataBarang.getString("stok"));
                if(stok < Integer.parseInt(txt_jumlah.getText())){
                    JOptionPane.showMessageDialog(null,"Maaf, Stok tidak mencukupi!");
                    txt_jumlah.setText("");
                    txt_jumlah.requestFocus();
                }else if(cekTabel(barang[0])){
                    JOptionPane.showMessageDialog(null,"Barang sudah dimasukan, masukan barang lain!");
                }else{
                    String data[] = {
                        barang[0],
                        barang[1],
                        txt_jumlah.getText(),
                        txt_harga.getText(),
                        txt_totalHarga.getText()
                    };
                    tabmode.addRow(data);
                    setTotal();
                    reset_text();
                    JOptionPane.showMessageDialog(null,"Data berhasil ditambahkan!");
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void cb_barangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_barangItemStateChanged
        // TODO add your handling code here:
        if(cb_barang.getSelectedIndex() > 0){
            String[] barang = cb_barang.getSelectedItem().toString().split("\\-", -1);
            setBarangDetail(barang[0]);
        }else{
            txt_totalHarga.setText("");
            txt_harga.setText("");
            txt_barangId.setText("");
            txt_jumlah.setText("");
        }
    }//GEN-LAST:event_cb_barangItemStateChanged

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        if(!txt_barangId.getText().trim().equals("")){
            setBarangDetail(txt_barangId.getText().trim());
        }
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void tabel_trxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_trxMouseClicked
        // TODO add your handling code here:
        try { 
            int row = tabel_trx.rowAtPoint(evt.getPoint());
            String barangid = tabel_trx.getValueAt(row, 0).toString();
            String barang = tabel_trx.getValueAt(row, 1).toString();
            String jumlah = tabel_trx.getValueAt(row, 2).toString();
            String harga = tabel_trx.getValueAt(row, 3).toString();
            String total = tabel_trx.getValueAt(row, 4).toString();
            txt_barangId.setText(String.valueOf(barangid));
            txt_harga.setText(String.valueOf(harga));
            txt_jumlah.setText(String.valueOf(jumlah));
            txt_totalHarga.setText(String.valueOf(total));
            cb_barang.setSelectedItem(barangid+"-"+barang);
            
            index = tabel_trx.getSelectedRow();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_tabel_trxMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenjualanForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenjualanForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_keluar;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_simpanAll;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JComboBox<String> cb_barang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_trx;
    private javax.swing.JTextField txt_barangId;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JTextField txt_totalHarga;
    private javax.swing.JLabel txt_totaltransaksi;
    // End of variables declaration//GEN-END:variables
}
